function(find_packages)
    find_package(Microsoft.GSL CONFIG REQUIRED)
    find_package(SDL2 CONFIG REQUIRED)
    find_package(tl-expected CONFIG REQUIRED)
    find_package(tl-optional CONFIG REQUIRED)
    find_package(glad CONFIG REQUIRED)
    find_package(magic_enum CONFIG REQUIRED)
endfunction()
